// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moAck.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MoAckRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MoAckRoot : GPBRootObject
@end

#pragma mark - MoAck

typedef GPB_ENUM(MoAck_FieldNumber) {
  MoAck_FieldNumber_DateTime = 1,
  MoAck_FieldNumber_MsgId = 2,
  MoAck_FieldNumber_Status = 3,
  MoAck_FieldNumber_Error = 4,
};

@interface MoAck : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *dateTime;
/** Test to see if @c dateTime has been set. */
@property(nonatomic, readwrite) BOOL hasDateTime;

/** ack received messageId */
@property(nonatomic, readwrite) int64_t msgId;

@property(nonatomic, readwrite) BOOL status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
