// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/Timestamp.pbobjc.h>
#else
 #import "google/protobuf/Timestamp.pbobjc.h"
#endif

 #import "MoMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MoMessageRoot

@implementation MoMessageRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MoMessageRoot_FileDescriptor

static GPBFileDescriptor *MoMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"demo"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MoMessage

@implementation MoMessage

@dynamic msgId;
@dynamic hasDateTime, dateTime;
@dynamic instanceIdMsb;
@dynamic instanceIdLsb;
@dynamic recipient;
@dynamic text;

typedef struct MoMessage__storage_ {
  uint32_t _has_storage_[1];
  GPBTimestamp *dateTime;
  NSString *recipient;
  NSString *text;
  int64_t msgId;
  uint64_t instanceIdMsb;
  uint64_t instanceIdLsb;
} MoMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "msgId",
        .dataTypeSpecific.className = NULL,
        .number = MoMessage_FieldNumber_MsgId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MoMessage__storage_, msgId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "dateTime",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBTimestamp),
        .number = MoMessage_FieldNumber_DateTime,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MoMessage__storage_, dateTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "instanceIdMsb",
        .dataTypeSpecific.className = NULL,
        .number = MoMessage_FieldNumber_InstanceIdMsb,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MoMessage__storage_, instanceIdMsb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "instanceIdLsb",
        .dataTypeSpecific.className = NULL,
        .number = MoMessage_FieldNumber_InstanceIdLsb,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MoMessage__storage_, instanceIdLsb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "recipient",
        .dataTypeSpecific.className = NULL,
        .number = MoMessage_FieldNumber_Recipient,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MoMessage__storage_, recipient),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "text",
        .dataTypeSpecific.className = NULL,
        .number = MoMessage_FieldNumber_Text,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(MoMessage__storage_, text),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MoMessage class]
                                     rootClass:[MoMessageRoot class]
                                          file:MoMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MoMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001\005\000\002\010\000\003\r\000\004\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
