// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moAck.proto

package net.hang321.sample.protobuf.data.proto;

public final class MoAckProtos {
  private MoAckProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MoAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.MoAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <pre>
     * ack received messageId
     * </pre>
     *
     * <code>int64 msgId = 2;</code>
     */
    long getMsgId();

    /**
     * <code>bool status = 3;</code>
     */
    boolean getStatus();

    /**
     * <code>string error = 4;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code demo.MoAck}
   */
  public  static final class MoAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.MoAck)
      MoAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MoAck.newBuilder() to construct.
    private MoAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoAck() {
      msgId_ = 0L;
      status_ = false;
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hang321.sample.protobuf.data.proto.MoAckProtos.internal_static_demo_MoAck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hang321.sample.protobuf.data.proto.MoAckProtos.internal_static_demo_MoAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.class, net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.Builder.class);
    }

    public static final int DATETIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public boolean hasDateTime() {
      return dateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return getDateTime();
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private long msgId_;
    /**
     * <pre>
     * ack received messageId
     * </pre>
     *
     * <code>int64 msgId = 2;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private boolean status_;
    /**
     * <code>bool status = 3;</code>
     */
    public boolean getStatus() {
      return status_;
    }

    public static final int ERROR_FIELD_NUMBER = 4;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 4;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.MoAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.MoAck)
        net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hang321.sample.protobuf.data.proto.MoAckProtos.internal_static_demo_MoAck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hang321.sample.protobuf.data.proto.MoAckProtos.internal_static_demo_MoAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.class, net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.Builder.class);
      }

      // Construct using net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }
        msgId_ = 0L;

        status_ = false;

        error_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hang321.sample.protobuf.data.proto.MoAckProtos.internal_static_demo_MoAck_descriptor;
      }

      public net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck getDefaultInstanceForType() {
        return net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck.getDefaultInstance();
      }

      public net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck build() {
        net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck buildPartial() {
        net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck result = new net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck(this);
        if (dateTimeBuilder_ == null) {
          result.dateTime_ = dateTime_;
        } else {
          result.dateTime_ = dateTimeBuilder_.build();
        }
        result.msgId_ = msgId_;
        result.status_ = status_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private com.google.protobuf.Timestamp dateTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public boolean hasDateTime() {
        return dateTimeBuilder_ != null || dateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (dateTime_ != null) {
            dateTime_ =
              com.google.protobuf.Timestamp.newBuilder(dateTime_).mergeFrom(value).buildPartial();
          } else {
            dateTime_ = value;
          }
          onChanged();
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
          onChanged();
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private long msgId_ ;
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 2;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 3;</code>
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 3;</code>
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 4;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 4;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.MoAck)
    }

    // @@protoc_insertion_point(class_scope:demo.MoAck)
    private static final net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck();
    }

    public static net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoAck>
        PARSER = new com.google.protobuf.AbstractParser<MoAck>() {
      public MoAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MoAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoAck> getParserForType() {
      return PARSER;
    }

    public net.hang321.sample.protobuf.data.proto.MoAckProtos.MoAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_MoAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_MoAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013moAck.proto\022\004demo\032\037google/protobuf/tim" +
      "estamp.proto\"c\n\005MoAck\022,\n\010dateTime\030\001 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\r\n\005msgId\030\002 \001" +
      "(\003\022\016\n\006status\030\003 \001(\010\022\r\n\005error\030\004 \001(\tB7\n&net" +
      ".hang321.sample.protobuf.data.protoB\013MoA" +
      "ckProtosH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_demo_MoAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_MoAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_MoAck_descriptor,
        new java.lang.String[] { "DateTime", "MsgId", "Status", "Error", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
