// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moMessage.proto

package net.hang321.sample.protobuf.data.proto;

public final class MoMsgProtos {
  private MoMsgProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.MoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msgId = 1;</code>
     */
    long getMsgId();

    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <pre>
     * most / least significant bits
     * </pre>
     *
     * <code>fixed64 instanceIdMsb = 3;</code>
     */
    long getInstanceIdMsb();

    /**
     * <code>fixed64 instanceIdLsb = 4;</code>
     */
    long getInstanceIdLsb();

    /**
     * <pre>
     * add "repeated" keyword for multiple recipients
     * </pre>
     *
     * <code>string recipient = 5;</code>
     */
    java.lang.String getRecipient();
    /**
     * <pre>
     * add "repeated" keyword for multiple recipients
     * </pre>
     *
     * <code>string recipient = 5;</code>
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <pre>
     * content
     * </pre>
     *
     * <code>string text = 6;</code>
     */
    java.lang.String getText();
    /**
     * <pre>
     * content
     * </pre>
     *
     * <code>string text = 6;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code demo.MoMessage}
   */
  public  static final class MoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.MoMessage)
      MoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MoMessage.newBuilder() to construct.
    private MoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoMessage() {
      msgId_ = 0L;
      instanceIdMsb_ = 0L;
      instanceIdLsb_ = 0L;
      recipient_ = "";
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hang321.sample.protobuf.data.proto.MoMsgProtos.internal_static_demo_MoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hang321.sample.protobuf.data.proto.MoMsgProtos.internal_static_demo_MoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.class, net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <code>int64 msgId = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int DATETIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    public boolean hasDateTime() {
      return dateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return getDateTime();
    }

    public static final int INSTANCEIDMSB_FIELD_NUMBER = 3;
    private long instanceIdMsb_;
    /**
     * <pre>
     * most / least significant bits
     * </pre>
     *
     * <code>fixed64 instanceIdMsb = 3;</code>
     */
    public long getInstanceIdMsb() {
      return instanceIdMsb_;
    }

    public static final int INSTANCEIDLSB_FIELD_NUMBER = 4;
    private long instanceIdLsb_;
    /**
     * <code>fixed64 instanceIdLsb = 4;</code>
     */
    public long getInstanceIdLsb() {
      return instanceIdLsb_;
    }

    public static final int RECIPIENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object recipient_;
    /**
     * <pre>
     * add "repeated" keyword for multiple recipients
     * </pre>
     *
     * <code>string recipient = 5;</code>
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * add "repeated" keyword for multiple recipients
     * </pre>
     *
     * <code>string recipient = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 6;
    private volatile java.lang.Object text_;
    /**
     * <pre>
     * content
     * </pre>
     *
     * <code>string text = 6;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * content
     * </pre>
     *
     * <code>string text = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.MoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.MoMessage)
        net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hang321.sample.protobuf.data.proto.MoMsgProtos.internal_static_demo_MoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hang321.sample.protobuf.data.proto.MoMsgProtos.internal_static_demo_MoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.class, net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.Builder.class);
      }

      // Construct using net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }
        instanceIdMsb_ = 0L;

        instanceIdLsb_ = 0L;

        recipient_ = "";

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hang321.sample.protobuf.data.proto.MoMsgProtos.internal_static_demo_MoMessage_descriptor;
      }

      public net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage getDefaultInstanceForType() {
        return net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage.getDefaultInstance();
      }

      public net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage build() {
        net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage buildPartial() {
        net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage result = new net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage(this);
        result.msgId_ = msgId_;
        if (dateTimeBuilder_ == null) {
          result.dateTime_ = dateTime_;
        } else {
          result.dateTime_ = dateTimeBuilder_.build();
        }
        result.instanceIdMsb_ = instanceIdMsb_;
        result.instanceIdLsb_ = instanceIdLsb_;
        result.recipient_ = recipient_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private long msgId_ ;
      /**
       * <code>int64 msgId = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>int64 msgId = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgId = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public boolean hasDateTime() {
        return dateTimeBuilder_ != null || dateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (dateTime_ != null) {
            dateTime_ =
              com.google.protobuf.Timestamp.newBuilder(dateTime_).mergeFrom(value).buildPartial();
          } else {
            dateTime_ = value;
          }
          onChanged();
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
          onChanged();
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private long instanceIdMsb_ ;
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 3;</code>
       */
      public long getInstanceIdMsb() {
        return instanceIdMsb_;
      }
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 3;</code>
       */
      public Builder setInstanceIdMsb(long value) {
        
        instanceIdMsb_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 3;</code>
       */
      public Builder clearInstanceIdMsb() {
        
        instanceIdMsb_ = 0L;
        onChanged();
        return this;
      }

      private long instanceIdLsb_ ;
      /**
       * <code>fixed64 instanceIdLsb = 4;</code>
       */
      public long getInstanceIdLsb() {
        return instanceIdLsb_;
      }
      /**
       * <code>fixed64 instanceIdLsb = 4;</code>
       */
      public Builder setInstanceIdLsb(long value) {
        
        instanceIdLsb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 instanceIdLsb = 4;</code>
       */
      public Builder clearInstanceIdLsb() {
        
        instanceIdLsb_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <pre>
       * add "repeated" keyword for multiple recipients
       * </pre>
       *
       * <code>string recipient = 5;</code>
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * add "repeated" keyword for multiple recipients
       * </pre>
       *
       * <code>string recipient = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * add "repeated" keyword for multiple recipients
       * </pre>
       *
       * <code>string recipient = 5;</code>
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * add "repeated" keyword for multiple recipients
       * </pre>
       *
       * <code>string recipient = 5;</code>
       */
      public Builder clearRecipient() {
        
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * add "repeated" keyword for multiple recipients
       * </pre>
       *
       * <code>string recipient = 5;</code>
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recipient_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * content
       * </pre>
       *
       * <code>string text = 6;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * content
       * </pre>
       *
       * <code>string text = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * content
       * </pre>
       *
       * <code>string text = 6;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * content
       * </pre>
       *
       * <code>string text = 6;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * content
       * </pre>
       *
       * <code>string text = 6;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.MoMessage)
    }

    // @@protoc_insertion_point(class_scope:demo.MoMessage)
    private static final net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage();
    }

    public static net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoMessage>
        PARSER = new com.google.protobuf.AbstractParser<MoMessage>() {
      public MoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoMessage> getParserForType() {
      return PARSER;
    }

    public net.hang321.sample.protobuf.data.proto.MoMsgProtos.MoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_MoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_MoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017moMessage.proto\022\004demo\032\037google/protobuf" +
      "/timestamp.proto\"\227\001\n\tMoMessage\022\r\n\005msgId\030" +
      "\001 \001(\003\022,\n\010dateTime\030\002 \001(\0132\032.google.protobu" +
      "f.Timestamp\022\025\n\rinstanceIdMsb\030\003 \001(\006\022\025\n\rin" +
      "stanceIdLsb\030\004 \001(\006\022\021\n\trecipient\030\005 \001(\t\022\014\n\004" +
      "text\030\006 \001(\tB7\n&net.hang321.sample.protobu" +
      "f.data.protoB\013MoMsgProtosH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_demo_MoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_MoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_MoMessage_descriptor,
        new java.lang.String[] { "MsgId", "DateTime", "InstanceIdMsb", "InstanceIdLsb", "Recipient", "Text", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
