// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtAck.proto

package net.hang321.sample.protobuf.data.proto;

public final class MtAckProtos {
  private MtAckProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MtAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.MtAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    boolean hasDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    com.google.protobuf.Timestamp getDateTime();
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

    /**
     * <pre>
     * most / least significant bits
     * </pre>
     *
     * <code>fixed64 instanceIdMsb = 2;</code>
     */
    long getInstanceIdMsb();

    /**
     * <code>fixed64 instanceIdLsb = 3;</code>
     */
    long getInstanceIdLsb();

    /**
     * <pre>
     * ack received messageId
     * </pre>
     *
     * <code>int64 msgId = 4;</code>
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code demo.MtAck}
   */
  public  static final class MtAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.MtAck)
      MtAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MtAck.newBuilder() to construct.
    private MtAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MtAck() {
      instanceIdMsb_ = 0L;
      instanceIdLsb_ = 0L;
      msgId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hang321.sample.protobuf.data.proto.MtAckProtos.internal_static_demo_MtAck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hang321.sample.protobuf.data.proto.MtAckProtos.internal_static_demo_MtAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.class, net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.Builder.class);
    }

    public static final int DATETIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp dateTime_;
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public boolean hasDateTime() {
      return dateTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public com.google.protobuf.Timestamp getDateTime() {
      return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
      return getDateTime();
    }

    public static final int INSTANCEIDMSB_FIELD_NUMBER = 2;
    private long instanceIdMsb_;
    /**
     * <pre>
     * most / least significant bits
     * </pre>
     *
     * <code>fixed64 instanceIdMsb = 2;</code>
     */
    public long getInstanceIdMsb() {
      return instanceIdMsb_;
    }

    public static final int INSTANCEIDLSB_FIELD_NUMBER = 3;
    private long instanceIdLsb_;
    /**
     * <code>fixed64 instanceIdLsb = 3;</code>
     */
    public long getInstanceIdLsb() {
      return instanceIdLsb_;
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private long msgId_;
    /**
     * <pre>
     * ack received messageId
     * </pre>
     *
     * <code>int64 msgId = 4;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.MtAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.MtAck)
        net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hang321.sample.protobuf.data.proto.MtAckProtos.internal_static_demo_MtAck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hang321.sample.protobuf.data.proto.MtAckProtos.internal_static_demo_MtAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.class, net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.Builder.class);
      }

      // Construct using net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }
        instanceIdMsb_ = 0L;

        instanceIdLsb_ = 0L;

        msgId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hang321.sample.protobuf.data.proto.MtAckProtos.internal_static_demo_MtAck_descriptor;
      }

      public net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck getDefaultInstanceForType() {
        return net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck.getDefaultInstance();
      }

      public net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck build() {
        net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck buildPartial() {
        net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck result = new net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck(this);
        if (dateTimeBuilder_ == null) {
          result.dateTime_ = dateTime_;
        } else {
          result.dateTime_ = dateTimeBuilder_.build();
        }
        result.instanceIdMsb_ = instanceIdMsb_;
        result.instanceIdLsb_ = instanceIdLsb_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private com.google.protobuf.Timestamp dateTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public boolean hasDateTime() {
        return dateTimeBuilder_ != null || dateTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.Timestamp getDateTime() {
        if (dateTimeBuilder_ == null) {
          return dateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        } else {
          return dateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder setDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTime_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder setDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          dateTime_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder mergeDateTime(com.google.protobuf.Timestamp value) {
        if (dateTimeBuilder_ == null) {
          if (dateTime_ != null) {
            dateTime_ =
              com.google.protobuf.Timestamp.newBuilder(dateTime_).mergeFrom(value).buildPartial();
          } else {
            dateTime_ = value;
          }
          onChanged();
        } else {
          dateTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          dateTime_ = null;
          onChanged();
        } else {
          dateTime_ = null;
          dateTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateTimeBuilder() {
        
        onChanged();
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder() {
        if (dateTimeBuilder_ != null) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          return dateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateTime = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateTime(),
                  getParentForChildren(),
                  isClean());
          dateTime_ = null;
        }
        return dateTimeBuilder_;
      }

      private long instanceIdMsb_ ;
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 2;</code>
       */
      public long getInstanceIdMsb() {
        return instanceIdMsb_;
      }
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 2;</code>
       */
      public Builder setInstanceIdMsb(long value) {
        
        instanceIdMsb_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * most / least significant bits
       * </pre>
       *
       * <code>fixed64 instanceIdMsb = 2;</code>
       */
      public Builder clearInstanceIdMsb() {
        
        instanceIdMsb_ = 0L;
        onChanged();
        return this;
      }

      private long instanceIdLsb_ ;
      /**
       * <code>fixed64 instanceIdLsb = 3;</code>
       */
      public long getInstanceIdLsb() {
        return instanceIdLsb_;
      }
      /**
       * <code>fixed64 instanceIdLsb = 3;</code>
       */
      public Builder setInstanceIdLsb(long value) {
        
        instanceIdLsb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 instanceIdLsb = 3;</code>
       */
      public Builder clearInstanceIdLsb() {
        
        instanceIdLsb_ = 0L;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ack received messageId
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.MtAck)
    }

    // @@protoc_insertion_point(class_scope:demo.MtAck)
    private static final net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck();
    }

    public static net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MtAck>
        PARSER = new com.google.protobuf.AbstractParser<MtAck>() {
      public MtAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MtAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MtAck> getParserForType() {
      return PARSER;
    }

    public net.hang321.sample.protobuf.data.proto.MtAckProtos.MtAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_MtAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_MtAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013mtAck.proto\022\004demo\032\037google/protobuf/tim" +
      "estamp.proto\"r\n\005MtAck\022,\n\010dateTime\030\001 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\025\n\rinstanceI" +
      "dMsb\030\002 \001(\006\022\025\n\rinstanceIdLsb\030\003 \001(\006\022\r\n\005msg" +
      "Id\030\004 \001(\003B7\n&net.hang321.sample.protobuf." +
      "data.protoB\013MtAckProtosH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_demo_MtAck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_MtAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_MtAck_descriptor,
        new java.lang.String[] { "DateTime", "InstanceIdMsb", "InstanceIdLsb", "MsgId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
